version: '3.8'

services:
  avito-segment:
    build: ./
    command: ./wait-for-postgres.sh db ./avito-segment
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=1474

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./schema/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=1474
    ports:
      - 5432:5432
